//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POIProxy
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity
    {
        public long activity_id { get; set; }
        public string user_id { get; set; }
        public string type { get; set; }
        public Nullable<int> content_id { get; set; }
        public string data { get; set; }
        public string status { get; set; }
        public Nullable<int> create_at { get; set; }
        public Nullable<int> update_at { get; set; }
    }
}
