//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POIProxy
{
    using System;
    using System.Collections.Generic;
    
    public partial class content
    {
        public long content_id { get; set; }
        public Nullable<int> site_id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public string module { get; set; }
        public string type { get; set; }
        public string source { get; set; }
        public Nullable<int> order { get; set; }
        public string user_id { get; set; }
        public string title { get; set; }
        public string title_url { get; set; }
        public string content1 { get; set; }
        public string details { get; set; }
        public string canonical { get; set; }
        public string access { get; set; }
        public string comments_allow { get; set; }
        public Nullable<int> comments_count { get; set; }
        public string geo_lat { get; set; }
        public string geo_long { get; set; }
        public string viewed { get; set; }
        public string approval { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
