//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POIProxy
{
    using System;
    using System.Collections.Generic;
    
    public partial class keyword
    {
        public string id { get; set; }
        public string keyword1 { get; set; }
    }
}
