//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POIProxy
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_attempts
    {
        public string id { get; set; }
        public byte[] ip_address { get; set; }
        public string login { get; set; }
        public Nullable<long> time { get; set; }
    }
}
