//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POIProxy
{
    using System;
    using System.Collections.Generic;
    
    public partial class presentation
    {
        public long pid { get; set; }
        public Nullable<int> course_id { get; set; }
        public string user_id { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> category { get; set; }
        public string creator { get; set; }
        public string reservation { get; set; }
        public Nullable<int> cover { get; set; }
        public Nullable<int> create_at { get; set; }
        public Nullable<int> update_at { get; set; }
        public Nullable<int> start_at { get; set; }
    }
}
