//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POIProxy
{
    using System;
    using System.Collections.Generic;
    
    public partial class relationship
    {
        public string relationship_id { get; set; }
        public Nullable<int> site_id { get; set; }
        public string owner_id { get; set; }
        public string user_id { get; set; }
        public string module { get; set; }
        public string type { get; set; }
        public string status { get; set; }
        public Nullable<int> created_at { get; set; }
        public Nullable<int> updated_at { get; set; }
    }
}
