//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POIProxy
{
    using System;
    using System.Collections.Generic;
    
    public partial class server
    {
        public long sid { get; set; }
        public string type { get; set; }
        public string ip { get; set; }
        public Nullable<int> port { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public string status { get; set; }
        public string audio_ip { get; set; }
        public int audio_port { get; set; }
    }
}
