//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POIProxy
{
    using System;
    using System.Collections.Generic;
    
    public partial class site
    {
        public long site_id { get; set; }
        public string url { get; set; }
        public string module { get; set; }
        public string type { get; set; }
        public string title { get; set; }
        public string favicon { get; set; }
    }
}
