//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POIProxy
{
    using System;
    using System.Collections.Generic;
    
    public partial class token
    {
        public long id { get; set; }
        public string token1 { get; set; }
        public string type { get; set; }
        public Nullable<int> expiration { get; set; }
        public Nullable<int> update_at { get; set; }
    }
}
