//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POIProxy
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_right
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public string type { get; set; }
        public Nullable<int> content_id { get; set; }
        public Nullable<int> user_right1 { get; set; }
        public Nullable<int> created_at { get; set; }
    }
}
