//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POIProxy
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_profile
    {
        public long id { get; set; }
        public string user_id { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string biography { get; set; }
        public string optional { get; set; }
        public Nullable<int> type { get; set; }
    }
}
