//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POIProxy
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string id { get; set; }
        public byte[] ip_address { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public string email { get; set; }
        public string activation_code { get; set; }
        public string forgotten_password_code { get; set; }
        public Nullable<long> forgotten_password_time { get; set; }
        public string remember_code { get; set; }
        public Nullable<long> created_on { get; set; }
        public Nullable<long> last_login { get; set; }
        public Nullable<bool> active { get; set; }
        public string accessRight { get; set; }
        public string name { get; set; }
    }
}
